const locationOptions = [
    { label: "Cairo", value: "CAIRO" },
  { label: "Giza", value: "GIZA" },
  { label: "Alexandria", value: "ALEXANDRIA" }, 
  { label: "Aswan", value: "ASWAN" },
  { label: "LUXOR", value: "LUXOR" },
  { label: "Qalyubia", value: "AL_QALYUBIYA" },
  { label: "Sharqia", value: "EASTERN" },
  { label: "Gharbia", value: "GHARBIA" },
  { label: "Faiyum", value: "FAIYUM" },
  { label: "Beni Suef", value: "BANI_SWEIF" },
  { label: "Minya", value: "AL_MINYA" },
  { label: "Assiut", value: "ASYUT" },
  { label: "Sohag", value: "SUHAJ" },
  { label: "Qena", value: "QENA" },
  { label: "Red Sea", value: "RED_SEA" }, 
  { label: "South Sinai", value: "SOUTH_SINAI" },
  { label: "North Sinai", value: "NORTH_SINAI" },
  { label: "New Valley", value: "NEW_VALLEY" },
  { label: "Damietta", value: "DAMIETTA" },
  { label: "Dakahlia", value: "AD_DAKAHLIYA" },
  { label: "Port Said", value: "PORT_SAID" },
  { label: "Suez", value: "SUEZ" },
  { label: "Ismailia", value: "AL_ISMAILIYA" },
  { label: "Menoufia", value: "AL_MINUFIYA" },
  { label: "Kafr El Sheikh", value: "KAFR_EL_SHEIKH" },
  { label: "Beheira", value: "THE_LAKE" },
  { label: "Matrouh", value: "MATRUH" },
];
export default locationOptions;
