const locationOptions = [
    { label: "Cairo", value: "CAIRO" },
  { label: "Giza", value: "GIZA" },
  { label: "Alexandria", value: "ALEXANDRIA" },
  { label: "Aswan", value: "ASWAN" },
  { label: "Luxor", value: "LUXOR" },
  { label: "Qalyubia", value: "QALYUBIA" },
  { label: "Sharqia", value: "SHARQIA" },
  { label: "Gharbia", value: "GHARBIJYA" },
  { label: "Faiyum", value: "FAIYUM" },
  { label: "Beni Suef", value: "BENI_SUEF" },
  { label: "Minya", value: "MINYA" },
  { label: "Assiut", value: "ASSIUT" },
  { label: "Sohag", value: "SOHAG" },
  { label: "Qena", value: "QENA" },
  { label: "Red Sea", value: "RED_SEA" },
  { label: "South Sinai", value: "SOUTH_SINAI" },
  { label: "North Sinai", value: "NORTH_SINAI" },
  { label: "New Valley", value: "NEW_VALLEY" },
  { label: "Damietta", value: "DAMIETTA" },
  { label: "Dakahlia", value: "DAKAHLIA" },
  { label: "Port Said", value: "PORT_SAID" },
  { label: "Suez", value: "SUEZ" },
  { label: "Ismailia", value: "ISMAILIA" },
  { label: "Menoufia", value: "MENOUFIA" },
  { label: "Kafr El Sheikh", value: "KAFR_EL_SHEIKH" },
  { label: "Beheira", value: "BEHEIRA" },
  { label: "Matrouh", value: "MATROUH" },
];
export default locationOptions;
